[colors.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"

[colors.dim]
black = "#32302f"
blue = "#076678"
cyan = "#427b58"
green = "#79740e"
magenta = "#8f3f71"
red = "#9d0006"
white = "#928374"
yellow = "#b57614"

[colors.normal]
black = "#1d2021"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#a89984"
yellow = "#d79921"

[colors.primary]
# Gruvbox Material Dark Medium (default)
background = "#282828"
foreground = "#d4be98"

# Gruvbox Material Dark Hard (highest contrast)
#background = "#1d2021"
#foreground = "#d4be98"

# Gruvbox Material Dark Soft (softest background)
#background = "#32302f"
#foreground = "#d4be98"

[env]
TERM = "xterm-256color"

[font]
size = 8
#normal.family = "Envy Code R"
normal.family = "EnvyCodeR Nerd Font" # https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/EnvyCodeR
builtin_box_drawing = true  # Better box drawing characters

[[hints.enabled]]
command = "browser-wrapper.sh"
hyperlinks = true
post_processing = true
regex = "(https?://|git://|ssh://|ftp://|ipfs:|ipns:|mailto:)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`\\\\]+"
mouse.enabled = true
binding = { key = "U", mods = "Control|Shift" }

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"


[window]
dynamic_padding = true
dynamic_title = true
padding = { x = 4, y = 4 }
decorations = "Full"  # Keep default - i3 will strip title bar anyway
startup_mode = "Windowed"  # Let i3 manage window placement
resize_increments = true  # Resize by cell size, prevents partial characters
