#!/bin/sh
# Ref: http://i3wm.org/docs/user-contributed/conky-i3bar.html

# Send the header so that i3bar knows we want to use JSON:
echo '{"version":1}'

# Begin the endless array.
echo '['

# We send an empty first array of blocks to make the loop simpler:
echo '[],'

# Now send blocks with information forever:
# Note: " in mpd song titles breaks JSON -- escape it via sed)
exec conky -c $HOME/.i3/conkyrc-$(hostname).lua | sed -ur 's/: \"(.*)\"(.*)\",/: \"\1\\"\2\",/g'
