#!/bin/bash
WORKSPACES=($(i3-msg -t get_workspaces|grep -oE '"num":[0-9]+' | cut -d: -f2 | sort -n))
OPEN=1
for ws in "${WORKSPACES[@]}"; do
    if [ "${ws}" == "${OPEN}" ]; then
        OPEN=$((OPEN + 1))
    fi
done
exec i3-msg workspace $OPEN
